package corbaConversion;


/**
* corbaConversion/IConversionRemote.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Conversion.idl
* Sunday, 26 November 2023 16:06:28 o'clock GMT+01:00
*/

public interface IConversionRemote extends IConversionRemoteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IConversionRemote
